### ISSUE TITLE
explore ggpk file

### ISSUE THREAD

**Issue by NothingSoup** [poeatlas/atlas-ui#1]
- [x] find out where atlas image is
- [x] find out where map icons are
- [x] find out where sextant icons are
- [x] find out where shaper orb icon is
- [x] find out where sextant circle icons are
- [x] find out where name of maps are stored
- [x] find out what stores the positions of maps
- [x] find out what stores the positions + area of the sextants

**Comment by ben-lei** [comment]
Can get already png'd files here (for example):
http://webcdn.pathofexile.com/image/art/2DItems/Maps/AtlasMaps/Academy1.png

**Comment by NothingSoup** [comment]
Within ROOT/Data/AtlasNode.dat:

- Maps each have a "Default_ItemVisualIdentityKey" that links to a table in BaseItemTypes.dat "ItemVisualIdentityKey".
- Each map also has a "Shaped_ItemVIsualIdentityKey" that indicates shaped version of map and links back to BaseItemTypes.dat attribute "ItemVisualIdentityKey"

Within ROOT/Data/BaseItemTypes.dat
- Contains names of all items and an ItemVisualIdentityKey attribute that is a foreign key to all items in game.
