### ISSUE TITLE
Versioned URLs

### ISSUE THREAD

**Issue by ben-lei** [poeatlas/atlas-ui#25]
Set up a system to deploy to GitHub as specific versions (e.g. poeatlas.github.io/3.1/?....., poeatlas.github.io/3.2/?.....)

**Comment by ben-lei** [comment]
This is done with d2d47f82a8a544a79a862ab201c9de5e76f9b7c5 -- maybe `this.history.push(process.env.PUBLIC_URL + "?" + historyStr);` should change to `this.history.push(process.env.PUBLIC_URL + "/?" + historyStr);`

**Comment by NothingSoup** [comment]
done
