### ISSUE TITLE
Remove all CSS style except border; rename it to .used.shaperOrb

### ISSUE THREAD

**Issue by ben-lei** [poeatlas/atlas-ui#5]
https://github.com/poeatlas/atlas-ui/blob/5714e66a4c3c6e469cdee52d46af225953972c0f/src/App.css#L42

A lot of repetitive code; can be made much simpler:

```
.shaperOrb {
  border: 2px dotted blue;
}

.used.shaperOrb {
  border: 2px dotted yellow;
}
```

**Comment by NothingSoup** [comment]
using separated blue/yellow border styles instead.
